// Code generated by protoc-gen-go. DO NOT EDIT.
// source: picture.proto

/*
Package pics is a generated protocol buffer package.

It is generated from these files:
	picture.proto

It has these top-level messages:
	Id
	Picture
*/
package pics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Picture struct {
	Pic []byte `protobuf:"bytes,1,opt,name=pic,proto3" json:"pic,omitempty"`
}

func (m *Picture) Reset()                    { *m = Picture{} }
func (m *Picture) String() string            { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()               {}
func (*Picture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Picture) GetPic() []byte {
	if m != nil {
		return m.Pic
	}
	return nil
}

func init() {
	proto.RegisterType((*Id)(nil), "pics.Id")
	proto.RegisterType((*Picture)(nil), "pics.Picture")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DownloadPic service

type DownloadPicClient interface {
	Download(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Picture, error)
}

type downloadPicClient struct {
	cc *grpc.ClientConn
}

func NewDownloadPicClient(cc *grpc.ClientConn) DownloadPicClient {
	return &downloadPicClient{cc}
}

func (c *downloadPicClient) Download(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Picture, error) {
	out := new(Picture)
	err := grpc.Invoke(ctx, "/pics.DownloadPic/Download", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DownloadPic service

type DownloadPicServer interface {
	Download(context.Context, *Id) (*Picture, error)
}

func RegisterDownloadPicServer(s *grpc.Server, srv DownloadPicServer) {
	s.RegisterService(&_DownloadPic_serviceDesc, srv)
}

func _DownloadPic_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadPicServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pics.DownloadPic/Download",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadPicServer).Download(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _DownloadPic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pics.DownloadPic",
	HandlerType: (*DownloadPicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Download",
			Handler:    _DownloadPic_Download_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "picture.proto",
}

func init() { proto.RegisterFile("picture.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc8, 0x4c, 0x2e,
	0x29, 0x2d, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0xc8, 0x4c, 0x2e, 0x56,
	0x12, 0xe1, 0x62, 0xf2, 0x4c, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x51, 0x92, 0xe6, 0x62, 0x0f, 0x80, 0x28, 0x16, 0x12, 0xe0, 0x62,
	0x2e, 0xc8, 0x4c, 0x06, 0xcb, 0xf1, 0x04, 0x81, 0x98, 0x46, 0x26, 0x5c, 0xdc, 0x2e, 0xf9, 0xe5,
	0x79, 0x39, 0xf9, 0x89, 0x29, 0x01, 0x99, 0xc9, 0x42, 0xaa, 0x5c, 0x1c, 0x30, 0xae, 0x10, 0x87,
	0x1e, 0xc8, 0x50, 0x3d, 0xcf, 0x14, 0x29, 0x5e, 0x08, 0x0b, 0x6a, 0x8a, 0x12, 0x43, 0x12, 0x1b,
	0xd8, 0x56, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x76, 0x10, 0xcf, 0x86, 0x00, 0x00,
	0x00,
}
