// Code generated by protoc-gen-go. DO NOT EDIT.
// source: picture.proto

/*
Package pics is a generated protocol buffer package.

It is generated from these files:
	picture.proto

It has these top-level messages:
	Id
	Picture
	Name
*/
package pics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id struct {
	Id string `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Picture struct {
	Pic []byte `protobuf:"bytes,1,opt,name=Pic,proto3" json:"Pic,omitempty"`
}

func (m *Picture) Reset()                    { *m = Picture{} }
func (m *Picture) String() string            { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()               {}
func (*Picture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Picture) GetPic() []byte {
	if m != nil {
		return m.Pic
	}
	return nil
}

type Name struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (m *Name) Reset()                    { *m = Name{} }
func (m *Name) String() string            { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()               {}
func (*Name) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Id)(nil), "pics.Id")
	proto.RegisterType((*Picture)(nil), "pics.Picture")
	proto.RegisterType((*Name)(nil), "pics.Name")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DownloadPic service

type DownloadPicClient interface {
	Download(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Picture, error)
}

type downloadPicClient struct {
	cc *grpc.ClientConn
}

func NewDownloadPicClient(cc *grpc.ClientConn) DownloadPicClient {
	return &downloadPicClient{cc}
}

func (c *downloadPicClient) Download(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Picture, error) {
	out := new(Picture)
	err := grpc.Invoke(ctx, "/pics.DownloadPic/Download", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DownloadPic service

type DownloadPicServer interface {
	Download(context.Context, *Id) (*Picture, error)
}

func RegisterDownloadPicServer(s *grpc.Server, srv DownloadPicServer) {
	s.RegisterService(&_DownloadPic_serviceDesc, srv)
}

func _DownloadPic_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadPicServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pics.DownloadPic/Download",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadPicServer).Download(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _DownloadPic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pics.DownloadPic",
	HandlerType: (*DownloadPicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Download",
			Handler:    _DownloadPic_Download_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "picture.proto",
}

// Client API for SearchPic service

type SearchPicClient interface {
	Search(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Picture, error)
}

type searchPicClient struct {
	cc *grpc.ClientConn
}

func NewSearchPicClient(cc *grpc.ClientConn) SearchPicClient {
	return &searchPicClient{cc}
}

func (c *searchPicClient) Search(ctx context.Context, in *Name, opts ...grpc.CallOption) (*Picture, error) {
	out := new(Picture)
	err := grpc.Invoke(ctx, "/pics.SearchPic/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SearchPic service

type SearchPicServer interface {
	Search(context.Context, *Name) (*Picture, error)
}

func RegisterSearchPicServer(s *grpc.Server, srv SearchPicServer) {
	s.RegisterService(&_SearchPic_serviceDesc, srv)
}

func _SearchPic_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchPicServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pics.SearchPic/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchPicServer).Search(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchPic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pics.SearchPic",
	HandlerType: (*SearchPicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchPic_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "picture.proto",
}

func init() { proto.RegisterFile("picture.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc8, 0x4c, 0x2e,
	0x29, 0x2d, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0xc8, 0x4c, 0x2e, 0x56,
	0x12, 0xe1, 0x62, 0xf2, 0x4c, 0x11, 0xe2, 0x03, 0x91, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41,
	0x4c, 0x9e, 0x29, 0x4a, 0xd2, 0x5c, 0xec, 0x01, 0x10, 0xc5, 0x42, 0x02, 0x5c, 0xcc, 0x01, 0x99,
	0xc9, 0x60, 0x39, 0x9e, 0x20, 0x10, 0x53, 0x49, 0x8a, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x55, 0x48,
	0x08, 0x42, 0x43, 0xb5, 0x81, 0xd9, 0x46, 0x26, 0x5c, 0xdc, 0x2e, 0xf9, 0xe5, 0x79, 0x39, 0xf9,
	0x89, 0x29, 0x01, 0x99, 0xc9, 0x42, 0xaa, 0x5c, 0x1c, 0x30, 0xae, 0x10, 0x87, 0x1e, 0xc8, 0x42,
	0x3d, 0xcf, 0x14, 0x29, 0x5e, 0x08, 0x0b, 0x6a, 0x83, 0x12, 0x83, 0x91, 0x11, 0x17, 0x67, 0x70,
	0x6a, 0x62, 0x51, 0x72, 0x06, 0x44, 0x0f, 0x1b, 0x84, 0x23, 0xc4, 0x05, 0x51, 0x07, 0x32, 0x18,
	0x43, 0x4f, 0x12, 0x1b, 0xd8, 0x17, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xf5, 0x0a,
	0xfb, 0xd6, 0x00, 0x00, 0x00,
}
